name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          echo "Starting deployment..."
          cd /app
          git pull origin main
          echo "Code updated"
          echo " Updating dependencies..."
          cd backend
          source venv/bin/activate
          pip install -r requirements-prod.txt
          echo "Dependencies updated"
          echo " Restarting service..."
          sudo systemctl restart eclipse-backend
          echo "Deployment completed at $(date)"